server:
  port: 8089

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8
    username: root
    password: 123Aa!!!
#    password: 123abc
    driver-class-name : com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall  # 配置底层功能，sql监控和防火墙
#      connectionInitSqls: set names utfm64
#      <property name="connectionInitSqls" value="set names utf8mb4;" />
#      aop-patterns: com.hhj.controller.* # 监控springbean

      # 详细配置stat
      filter:
        stat:
          slow-sql-millis: 1000 #定义一秒以上的为慢SQL
          db-type: mysql
          log-slow-sql: true # 记录慢SQL
        wall:
          config:
#            drop-table-allow: false # 拦截所有删表方法
          db-type: mysql
          enabled: true #防止SQL注入问题

      #配置监控页面
      stat-view-servlet:
        enabled: true   # 开启监控页
#        login-username: admin
#        login-password: admin

      # 配置监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


  redis:
    host: 127.0.0.1
    port: 6379
    password: 123abc

# 日志配置
logging:
  level:
    com.hhj.blogbackend.mapper: debug # 设置指定包的日志级别（未指定的包按照root的日志级别执行）
    root: info  # 定义项目日志级别（默认是info）
  file:
    path: /springboot/log # 配置日志输出到当前项目所在磁盘根路径下的/springboot/log目录下（也可以使用绝对路径）
    name: springboot-blog.log
  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'




# 配置mybatis-plus
mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.hhj.blogbackend
#  type-enums-package: com.hhj.blogbackend.pojo com.hhj.blogbackend.dto

#shiro-redis:
#  enabled: true
#  redis-manager:
#    host: 127.0.0.1:6379
#token配置
blog:
  jwt:
    # 加密秘钥
    secret: zrf5202e34348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
#
#shiro-redis:
#  enabled: true
#  redis-manager:
#    host:127.0.0.1:6379

